spring:
    profiles:
        avtive:
        - dev
---
spring:
    profiles: dev #开发环境
    application:
        name: xavier-config-leon-dev
---
spring:
    profiles: test #测试环境
    application:
        name: xavier-config-leon-test
#保存格式为utf-8
